import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Sale, Product, User, Setting } from '@shared/schema';

interface ReportData {
  title: string;
  dateRange: { start: Date; end: Date };
  storeName: string;
  storeAddress: string;
  storePhone: string;
}

interface SalesReportData extends ReportData {
  sales: Sale[];
  products: Product[];
  totalSales: number;
  totalTransactions: number;
  averageTransaction: number;
  taxAmount: number;
}

interface InventoryReportData extends ReportData {
  products: Product[];
  totalValue: number;
  lowStockItems: Product[];
  outOfStockItems: Product[];
}

export class PDFGenerator {
  private doc: jsPDF;

  constructor() {
    this.doc = new jsPDF();
  }

  private addHeader(reportData: ReportData) {
    const { doc } = this;
    
    // Store logo placeholder
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(reportData.storeName, 20, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(reportData.storeAddress, 20, 35);
    doc.text(reportData.storePhone, 20, 42);
    
    // Report title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(reportData.title, 20, 60);
    
    // Date range
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const dateText = `Period: ${reportData.dateRange.start.toLocaleDateString()} - ${reportData.dateRange.end.toLocaleDateString()}`;
    doc.text(dateText, 20, 70);
    
    // Generation timestamp
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 77);
    
    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 85, 190, 85);
    
    return 90; // Return Y position for next content
  }

  private addFooter() {
    const { doc } = this;
    const pageHeight = doc.internal.pageSize.height;
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by MiniMart POS System', 20, pageHeight - 20);
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, 170, pageHeight - 20);
  }

  generateSalesReport(data: SalesReportData): jsPDF {
    this.doc = new jsPDF();
    let currentY = this.addHeader(data);
    
    // Summary section
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Sales Summary', 20, currentY + 10);
    
    const summaryData = [
      ['Total Sales', `KSH ${data.totalSales.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['Total Transactions', data.totalTransactions.toString()],
      ['Average Transaction', `KSH ${data.averageTransaction.toFixed(2)}`],
      ['Tax Collected (VAT)', `KSH ${data.taxAmount.toFixed(2)}`]
    ];
    
    autoTable(this.doc, {
      startY: currentY + 20,
      head: [['Metric', 'Value']],
      body: summaryData,
      theme: 'grid',
      headStyles: { fillColor: [66, 139, 202] },
      margin: { left: 20, right: 20 }
    });
    
    currentY = (this.doc as any).lastAutoTable.finalY + 20;
    
    // Payment methods breakdown
    const paymentMethods = ['cash', 'mpesa', 'credit'];
    const paymentData = paymentMethods.map(method => {
      const methodSales = data.sales.filter(sale => sale.paymentMethod === method);
      const methodTotal = methodSales.reduce((sum, sale) => sum + parseFloat(sale.total), 0);
      const percentage = data.totalSales > 0 ? (methodTotal / data.totalSales) * 100 : 0;
      
      return [
        method.toUpperCase(),
        methodSales.length.toString(),
        `KSH ${methodTotal.toFixed(2)}`,
        `${percentage.toFixed(1)}%`
      ];
    });
    
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Payment Methods Breakdown', 20, currentY);
    
    autoTable(this.doc, {
      startY: currentY + 10,
      head: [['Payment Method', 'Transactions', 'Amount', 'Percentage']],
      body: paymentData,
      theme: 'grid',
      headStyles: { fillColor: [66, 139, 202] },
      margin: { left: 20, right: 20 }
    });
    
    currentY = (this.doc as any).lastAutoTable.finalY + 20;
    
    // Detailed transactions
    if (data.sales.length > 0) {
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text('Transaction Details', 20, currentY);
      
      const transactionData = data.sales.slice(0, 50).map(sale => [
        sale.id.toString(),
        new Date(sale.createdAt).toLocaleString(),
        `KSH ${parseFloat(sale.total).toFixed(2)}`,
        sale.paymentMethod.toUpperCase(),
        sale.status.toUpperCase()
      ]);
      
      autoTable(this.doc, {
        startY: currentY + 10,
        head: [['ID', 'Date/Time', 'Amount', 'Payment', 'Status']],
        body: transactionData,
        theme: 'striped',
        headStyles: { fillColor: [66, 139, 202] },
        margin: { left: 20, right: 20 },
        styles: { fontSize: 8 }
      });
    }
    
    this.addFooter();
    return this.doc;
  }

  generateInventoryReport(data: InventoryReportData): jsPDF {
    this.doc = new jsPDF();
    let currentY = this.addHeader(data);
    
    // Inventory summary
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Inventory Summary', 20, currentY + 10);
    
    const summaryData = [
      ['Total Products', data.products.length.toString()],
      ['Total Inventory Value', `KSH ${data.totalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['Low Stock Items', data.lowStockItems.length.toString()],
      ['Out of Stock Items', data.outOfStockItems.length.toString()]
    ];
    
    autoTable(this.doc, {
      startY: currentY + 20,
      head: [['Metric', 'Value']],
      body: summaryData,
      theme: 'grid',
      headStyles: { fillColor: [40, 167, 69] },
      margin: { left: 20, right: 20 }
    });
    
    currentY = (this.doc as any).lastAutoTable.finalY + 20;
    
    // Product details
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Product Details', 20, currentY);
    
    const productData = data.products.map(product => {
      const value = product.stock * parseFloat(product.costPrice);
      const status = product.stock === 0 ? 'OUT' : 
                   product.stock <= product.minStock ? 'LOW' : 'OK';
      
      return [
        product.name,
        product.sku,
        product.category,
        product.stock.toString(),
        `KSH ${parseFloat(product.price).toFixed(2)}`,
        `KSH ${value.toFixed(2)}`,
        status
      ];
    });
    
    autoTable(this.doc, {
      startY: currentY + 10,
      head: [['Product', 'SKU', 'Category', 'Stock', 'Price', 'Value', 'Status']],
      body: productData,
      theme: 'striped',
      headStyles: { fillColor: [40, 167, 69] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 8 },
      columnStyles: {
        6: { 
          cellWidth: 15,
          halign: 'center',
          fillColor: (data: any) => {
            const status = data.cell.raw;
            if (status === 'OUT') return [220, 53, 69];
            if (status === 'LOW') return [255, 193, 7];
            return [40, 167, 69];
          },
          textColor: 255
        }
      }
    });
    
    this.addFooter();
    return this.doc;
  }

  generateDailySalesReport(sales: Sale[], date: Date, settings: Setting[]): jsPDF {
    this.doc = new jsPDF();
    
    const settingsMap = settings.reduce((acc, setting) => {
      acc[setting.key] = setting.value;
      return acc;
    }, {} as Record<string, string>);
    
    const reportData: SalesReportData = {
      title: 'Daily Sales Report',
      dateRange: { 
        start: new Date(date.getFullYear(), date.getMonth(), date.getDate()),
        end: new Date(date.getFullYear(), date.getMonth(), date.getDate(), 23, 59, 59)
      },
      storeName: settingsMap.store_name || 'MiniMart Express',
      storeAddress: settingsMap.store_address || '123 Main Street, Nairobi',
      storePhone: settingsMap.store_phone || '+254 700 123456',
      sales,
      products: [],
      totalSales: sales.reduce((sum, sale) => sum + parseFloat(sale.total), 0),
      totalTransactions: sales.length,
      averageTransaction: sales.length > 0 ? sales.reduce((sum, sale) => sum + parseFloat(sale.total), 0) / sales.length : 0,
      taxAmount: sales.reduce((sum, sale) => sum + parseFloat(sale.tax), 0)
    };
    
    return this.generateSalesReport(reportData);
  }

  generateReceipt(sale: any, saleItems: any[], settings: Setting[]): jsPDF {
    this.doc = new jsPDF({
      format: [80, 200], // Thermal receipt size (80mm width)
      unit: 'mm'
    });
    
    const settingsMap = settings.reduce((acc, setting) => {
      acc[setting.key] = setting.value;
      return acc;
    }, {} as Record<string, string>);
    
    let currentY = 10;
    
    // Store header
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    const storeName = settingsMap.store_name || 'MINIMART EXPRESS';
    this.doc.text(storeName, 40, currentY, { align: 'center' });
    
    currentY += 8;
    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    const storeAddress = settingsMap.store_address || '123 Main Street, Nairobi';
    this.doc.text(storeAddress, 40, currentY, { align: 'center' });
    
    currentY += 5;
    const storePhone = settingsMap.store_phone || '+254 700 123456';
    this.doc.text(`Tel: ${storePhone}`, 40, currentY, { align: 'center' });
    
    currentY += 10;
    this.doc.setLineWidth(0.1);
    this.doc.line(5, currentY, 75, currentY);
    
    // Receipt details
    currentY += 5;
    this.doc.text(`Receipt #: ${sale.id}`, 5, currentY);
    currentY += 4;
    this.doc.text(`Date: ${new Date(sale.createdAt).toLocaleString()}`, 5, currentY);
    currentY += 4;
    this.doc.text(`Cashier: ${sale.cashierName || 'System'}`, 5, currentY);
    
    currentY += 7;
    this.doc.line(5, currentY, 75, currentY);
    
    // Items
    currentY += 5;
    saleItems.forEach(item => {
      this.doc.text(item.product?.name || 'Product', 5, currentY);
      currentY += 4;
      this.doc.text(`${item.quantity} x ${parseFloat(item.unitPrice).toFixed(2)}`, 5, currentY);
      this.doc.text(`${parseFloat(item.total).toFixed(2)}`, 70, currentY, { align: 'right' });
      currentY += 6;
    });
    
    currentY += 2;
    this.doc.line(5, currentY, 75, currentY);
    
    // Totals
    currentY += 5;
    this.doc.text('Subtotal:', 5, currentY);
    this.doc.text(`KSH ${parseFloat(sale.subtotal).toFixed(2)}`, 70, currentY, { align: 'right' });
    
    currentY += 4;
    this.doc.text('VAT (16%):', 5, currentY);
    this.doc.text(`KSH ${parseFloat(sale.tax).toFixed(2)}`, 70, currentY, { align: 'right' });
    
    currentY += 5;
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('TOTAL:', 5, currentY);
    this.doc.text(`KSH ${parseFloat(sale.total).toFixed(2)}`, 70, currentY, { align: 'right' });
    
    currentY += 7;
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Payment: ${sale.paymentMethod?.toUpperCase()}`, 5, currentY);
    
    if (sale.mpesaRef) {
      currentY += 4;
      this.doc.text(`M-Pesa Ref: ${sale.mpesaRef}`, 5, currentY);
    }
    
    currentY += 10;
    this.doc.line(5, currentY, 75, currentY);
    
    // Footer
    currentY += 5;
    const receiptHeader = settingsMap.receipt_header || 'Thank you for shopping with us!';
    this.doc.text(receiptHeader, 40, currentY, { align: 'center' });
    
    currentY += 5;
    const receiptFooter = settingsMap.receipt_footer || 'Visit again soon.';
    this.doc.text(receiptFooter, 40, currentY, { align: 'center' });
    
    return this.doc;
  }

  downloadPDF(filename: string) {
    this.doc.save(filename);
  }

  getPDFBlob(): Blob {
    return this.doc.output('blob');
  }

  getPDFDataUri(): string {
    return this.doc.output('datauristring');
  }
}

export const pdfGenerator = new PDFGenerator();